name: 'Download extension'
description: 'Download extension'
inputs:
  url:
    description: "url"
    required: true
  target_path:
    description: "target_path"
    required: true 

runs:
  using: 'composite'
  steps:
    - name: Parse JSON and download extension
      shell: sh
      run: |
        echo "${{ inputs.url }}"
        echo "${{ inputs.target_path }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}
