name: 'Download extension'
description: 'Download extension'
inputs:
  config_file:
    description: "Path to JSON config describing extension (contains 'url')"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Parse JSON and download extension
      shell: sh
      run: |
        echo "Reading config from: $CONFIG_FILE"
        CONFIG_FILE="${{ inputs.config_file }}"
        DOWNLOAD_URL=$(jq -r '.url' "$CONFIG_FILE")
        TARGET_PATH=$(jq -r '.target_path' "$CONFIG_FILE")
        DIRNAME="$(dirname "$TARGET_PATH")"

        curl -L -H "Authorization: token $GITHUB_TOKEN" \
        -o "$TARGET_PATH" "$DOWNLOAD_URL"

        ls -la "$DIRNAME"
      env:
        GITHUB_TOKEN: ${{ github.token }}