name: 'Download extension'
description: 'Download extension'
inputs:
  url:
    description: "url"
    required: true
  target_path:
    description: "target_path"
    required: true 

runs:
  using: 'composite'
  steps:
    - name: Parse JSON and download extension
      shell: sh
      run: |
        curl -L -H "Authorization: token $GITHUB_TOKEN" \
          -o "${{ inputs.target_path }}" "${{ inputs.url }}"

        ls -la "$(dirname "${{ inputs.target_path }}")"
      env:
        GITHUB_TOKEN: ${{ github.token }}
